# Generated by Django 5.0.4 on 2024-04-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image_travelplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelplan',
            old_name='date',
            new_name='date_from',
        ),
        migrations.AddField(
            model_name='travelplan',
            name='date_to',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='categories',
            field=models.CharField(choices=[('Must See Attractions', 'Must See Attractions'), ('Hidden Gems', 'Hidden Gems'), ('Shopping', 'Shopping'), ('Great Food', 'Great Food'), ('Cultural Heritage', 'Cultural Heritage'), ('Art and Theater', 'Art and Theater')], max_length=50, null=True),
        ),
    ]
