# Generated by Django 5.0.4 on 2024-04-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_date_travelplan_date_from_travelplan_date_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelplan',
            name='price',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
